from selenium_framework.automationexercise.pages.account_register import account_register_page
from selenium_framework.automationexercise.pages.login_page import login_page
from selenium_framework.automationexercise.pages.main_page import main_page
